### ISSUE TITLE
atari-py dependency doesn't seem maintained

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy-tutorials#69]
The reinforcement learning tutorial depends on [atari-py](https://github.com/openai/atari-py) which doesn't seem to be actively maintained (last commit Aug 2019). The README indicates that it's in "maintenance mode" but there haven't been any active developments and the [wheels are out of date](https://pypi.org/project/atari-py/#history). This latter necessitates that wheels be built locally, requiring cmake.

I'm not familiar with gym or atari-py so I don't know if there are any newer packages or viable alternatives. Does anyone know of any viable alternatives?

**Comment by melissawm** [comment]
Installing `gym[atari]` from pip was enough for me, but maybe this has changed. @8bitmp3 any ideas?

**Comment by rossbar** [comment]
It will work if you have cmake on your system (at least on *nix platforms). The wheel is being built locally though.

**Comment by 8bitmp3** [comment]
Thanks for bringing this up @rossbar. Is this about `config.yaml`?:

```
version: 2
jobs:
  build-docs:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.8.5-buster
    steps:
      - checkout

      - run:
          name: Install deps for building atari-py
          command: sudo apt-get install -y cmake ffmpeg
...
```

As @melissawm, `gym[atari]` should be enough to run the Atari simulation (`pip install gym[atari]` (https://github.com/openai/gym, last commit as of today was on Feb 16, 2021)). In the tutorial, we state that the user needs to install `jupyter-book` and `gym[atari]`, so hopefully that's enough for them to try it out.
